# tests/test_atlas_viewer_assets.py
from pathlib import Path

from viva_human_atlas.atlas_pack import build_atlas_manifest, write_atlas_pack

VIZ = Path(__file__).resolve().parents[1] / "studies" / "hra-atlas-browser" / "viz" / "atlas"


def test_viewer_assets_exist_and_are_wired():
    # encoding="utf-8" pinned explicitly: importing viva_human_atlas (via
    # pbg_simbio/viva_superpowers) flips the process's ambient locale
    # encoding to ASCII in some environments, which breaks the default
    # `Path.read_text()` on these UTF-8 files (em-dash, ellipsis). Same
    # class of issue already worked around in composite_generator.py.
    html = (VIZ / "index.html").read_text(encoding="utf-8")
    js = (VIZ / "viewer.js").read_text(encoding="utf-8")
    assert 'src="./viewer.js"' in html
    assert ("config.json" in js and "atlas.json" in js.lower()) or "cfg.atlas" in js
    assert "organ-select" in html          # the selector element
    assert "biomodels-panel" in html       # the model list panel
    assert "three@0.160.0" in html         # pinned importmap


def test_viewer_has_overview_mode():
    js = (VIZ / "viewer.js").read_text(encoding="utf-8")
    html = (VIZ / "index.html").read_text(encoding="utf-8")
    assert "overview_glb" in js or "cfg.overview_glb" in js
    assert "loadOverview" in js
    assert "__overview__" in html or "__overview__" in js  # the overview select value


def test_write_atlas_pack_only_writes_json(tmp_path):
    # write_atlas_pack must never create/overwrite the hand-written
    # index.html/viewer.js — those are committed viewer assets, not
    # generated by the build script. Only the JSON data files are its job.
    catalog = {"organ_index": {}, "organ_to_models": {}, "biomodel_dos": []}
    manifest = build_atlas_manifest(catalog)
    write_atlas_pack(
        tmp_path,
        manifest=manifest,
        coverage={"coverage": [], "summary": {}},
        overview_glb_url=None,
    )
    assert not (tmp_path / "index.html").exists()
    assert not (tmp_path / "viewer.js").exists()
    assert (tmp_path / "atlas.json").exists()
    assert (tmp_path / "coverage.json").exists()
    assert (tmp_path / "config.json").exists()
