# tests/test_atlas_viewer_assets.py
from pathlib import Path

from viva_human_atlas.atlas_pack import build_atlas_manifest, write_atlas_pack

VIZ = Path(__file__).resolve().parents[1] / "studies" / "hra-atlas-browser" / "viz" / "atlas"


def test_viewer_assets_exist_and_are_wired():
    # encoding="utf-8" pinned explicitly: importing viva_human_atlas (via
    # pbg_simbio/viva_superpowers) flips the process's ambient locale
    # encoding to ASCII in some environments, which breaks the default
    # `Path.read_text()` on these UTF-8 files (em-dash, ellipsis). Same
    # class of issue already worked around in composite_generator.py.
    html = (VIZ / "index.html").read_text(encoding="utf-8")
    js = (VIZ / "viewer.js").read_text(encoding="utf-8")
    assert 'src="./viewer.js"' in html
    assert ("config.json" in js and "atlas.json" in js.lower()) or "cfg.atlas" in js
    assert "organ-list" in html            # the left organ menu
    assert "biomodels-panel" in html       # the model list panel
    assert "three@0.160.0" in html         # pinned importmap


def test_viewer_has_multiselect_menu():
    # The viewer offers a left menu of all organs with parsimony-style
    # selection: click a row to add/remove, "only" to isolate, "All modeled"
    # to compose every modeled organ together, "None" to clear.
    js = (VIZ / "viewer.js").read_text(encoding="utf-8")
    html = (VIZ / "index.html").read_text(encoding="utf-8")
    assert "btn-all-modeled" in html and "btn-all" in html and "btn-none" in html
    assert "btn-center" in html                        # recenter-view control
    assert "organ-search" in html                     # filter box
    assert "selectOnly" in js                          # isolate one organ
    assert "selectMany" in js and "modeledKeys" in js  # show all modeled together
    assert "allKeys" in js                             # "All" = all 50 organs
    assert "function toggle" in js                     # click-through add/remove
    assert "buildMenu" in js                           # renders the organ list


def test_viewer_groups_by_organ_system():
    # The menu groups organs into collapsible anatomical systems with
    # per-system toggle ("gchk") and "only" (onlySystem) controls.
    js = (VIZ / "viewer.js").read_text(encoding="utf-8")
    assert "organsBySystem" in js
    assert "toggleSystem" in js and "onlySystem" in js
    assert "group-head" in js and "collapsed" in js    # collapsible headers
    assert "viridis" in js.lower()                     # high-contrast colormap


def test_viewer_has_model_keyword_search():
    # A keyword search on the model side (right panel) filters models and
    # recolors the shown organs by how many of their models match, so you see
    # WHERE the matching models are represented.
    js = (VIZ / "viewer.js").read_text(encoding="utf-8")
    html = (VIZ / "index.html").read_text(encoding="utf-8")
    assert "model-search" in html                       # the model keyword box
    assert "matchingModels" in js                       # per-organ keyword match
    assert "recolorShown" in js                         # recolor organs by match
    assert "renderModelSearch" in js                    # results grouped by organ


def test_write_atlas_pack_only_writes_json(tmp_path):
    # write_atlas_pack must never create/overwrite the hand-written
    # index.html/viewer.js — those are committed viewer assets, not
    # generated by the build script. Only the JSON data files are its job.
    catalog = {"organ_index": {}, "organ_to_models": {}, "biomodel_dos": []}
    manifest = build_atlas_manifest(catalog)
    write_atlas_pack(
        tmp_path,
        manifest=manifest,
        coverage={"coverage": [], "summary": {}},
        overview_glb_url=None,
    )
    assert not (tmp_path / "index.html").exists()
    assert not (tmp_path / "viewer.js").exists()
    assert (tmp_path / "atlas.json").exists()
    assert (tmp_path / "coverage.json").exists()
    assert (tmp_path / "config.json").exists()
