#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python hra-integration.py

Figures are written to:  reports/published/dashboard/investigation-notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # HRA API Integration — Datasets, Ontology, and BioModel Digital Objects
#
# _Investigation `hra-integration` — coder reproduction notebook._
#
# **Question.** Can we pull HRA datasets/knowledge via the live CCF API (reference organs,
# cell-type terms, anatomical-structure terms) and link BioModels to HRA
# anatomy (Uberon organs) via a transparent biomodel Digital Object +
# organ->models index — and, having built that index, actually get the
# resulting models onto the HRA atlas as something a user can see?
#
# Builds the HRA (Human Reference Atlas) side of the fetch-and-compare
# spine, then closes the loop into the Atlas Browser: a thin CCF-API
# client (reference organs, cell-type terms, anatomical-structure terms);
# a biomodel Digital Object annotation layer with two complementary organ
# matchers — name-synonym matching over BioModels titles, and
# annotation-based matching over each model's own SBML MIRIAM/BTO
# metadata; a measured comparison of how much recall the annotation
# matcher adds over name-only matching; and the HRA Atlas Browser
# (`studies/hra-atlas-browser/viz/atlas/`) that renders the resulting
# organ->models index as an interactive 3D atlas a user can actually see
# biomodels attached to.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/Users/eranagmon/code/viva-human-atlas--lint').is_dir():
    REPO = Path('/Users/eranagmon/code/viva-human-atlas--lint')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from viva_human_atlas.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

# ## Study: `hra-reference-organs`
#
# **Question.** Does the HRA CCF API's reference-organs endpoint load into a Step-driven
# composite, giving an Uberon-keyed organ set (with per-sex GLB assets)?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: hra-reference-organs ===
STUDY = 'hra-reference-organs'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `hra-cell-types`
#
# **Question.** Does the HRA CCF API's cell-type-term-occurences endpoint load into a
# Step-driven composite, giving a Cell Ontology (CL) term occurrence list?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: hra-cell-types ===
STUDY = 'hra-cell-types'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `hra-anatomical-structures`
#
# **Question.** Does the HRA CCF API's ontology-term-occurences endpoint load into a
# Step-driven composite, giving an anatomical-structure term occurrence list?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: hra-anatomical-structures ===
STUDY = 'hra-anatomical-structures'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `glucose-biomodel-do`
#
# **Question.** Can glucose-regulation BioModels be annotated with HRA Uberon organ terms
# (via transparent synonym matching) and inverted into an organ->models index?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: glucose-biomodel-do ===
STUDY = 'glucose-biomodel-do'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `annotation-organ-matching`
#
# **Question.** How does a BioModels entry get tagged with an HRA Uberon organ when the
# match comes from its embedded SBML MIRIAM annotations rather than its
# name — and which biological CVTerm qualifiers / ontologies actually carry
# that organ signal?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: annotation-organ-matching ===
STUDY = 'annotation-organ-matching'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `annotation-recall-gain`
#
# **Question.** How much organ/model coverage does annotation-based organ matching (SBML
# MIRIAM + BTO crosswalk) add over the existing name-synonym matcher
# (`glucose-biomodel-do`/`corpus-coverage`), across the full 1,096-model
# curated BioModels corpus?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: annotation-recall-gain ===
STUDY = 'annotation-recall-gain'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Open decisions
# - Resolved: SBML MIRIAM/BTO annotation matching (annotation-organ-matching, annotation-recall-gain) raised full-corpus recall from 82/1,096 (7.5%) to a 167/1,096 (15.2%) union across 14 organs. Should the union (not name-only) become the default organ->models index the Atlas Browser and downstream coverage studies key off?
# - How much more organ coverage would extending the 32-entry BTO->organ crosswalk unlock?
