#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python hra-3d.py

Figures are written to:  reports/published/dashboard/investigation-notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # HRA-3D — Model Coverage on the Human Reference Atlas 3D Anatomy
#
# _Investigation `hra-3d` — coder reproduction notebook._
#
# **Question.** Which of the HRA's 1,730 Uberon-keyed anatomical structures (2,295 raw
# ASCT+B-3D crosswalk rows, 114 source-organ GLBs) are covered by a
# mechanistic model — at a single query's scale and at the full
# 1,096-model curated-corpus scale — and can we view that coverage/linkage
# directly on the 3D anatomy?
#
# Builds the 3D-anatomy side of the fetch-and-compare spine: the full
# ASCT+B-3D crosswalk and a glomerulus FTU digital object, organ-
# granularity model coverage crossed with the biomodel-DO index at both
# query scale and full-corpus scale, model->AS->GLB-node spatial linkage,
# and a materialized three.js viewer pack.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/Users/eranagmon/code/viva-human-atlas').is_dir():
    REPO = Path('/Users/eranagmon/code/viva-human-atlas')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from viva_human_atlas.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

# ## Study: `hra-3d-crosswalk`
#
# **Question.** Does the HRA CDN's ASCT+B-3D models crosswalk load into a Step-driven
# composite, giving the full 1,400+ anatomical-structure (AS) tree — not
# just the ~81 per-organ reference-organ GLBs — with resolvable Uberon CURIEs
# and source-organ GLB names?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: hra-3d-crosswalk ===
STUDY = 'hra-3d-crosswalk'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `model-coverage-3d`
#
# **Question.** Of the HRA ASCT+B-3D crosswalk's 1,400+ anatomical structures (and ~81
# reference organs), which are covered by a mechanistic model — and can
# that coverage be viewed directly on the 3D anatomy?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: model-coverage-3d ===
STUDY = 'model-coverage-3d'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `spatial-linkage`
#
# **Question.** For each biomodel-DO organ annotation, exactly which ASCT+B-3D crosswalk
# GLB scene node(s) does it correspond to — precise enough for a 3D viewer
# to color/label the right node per model?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: spatial-linkage ===
STUDY = 'spatial-linkage'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `ftu-glomerulus`
#
# **Question.** Does the HRA CDN's glomerulus 3D functional-tissue-unit (FTU) digital
# object load into a Step-driven composite, giving a sub-organ-scale 3D
# asset (below the per-organ reference-organ GLBs) that could anchor
# finer-grained model coverage?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: ftu-glomerulus ===
STUDY = 'ftu-glomerulus'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `corpus-coverage`
#
# **Question.** Of the HRA ASCT+B-3D crosswalk's 1,730 Uberon-keyed anatomical structures
# (across 114 source-organ GLBs), how many are covered once every curated
# BioModels model — not just a narrow search query — is crossed against
# them, and does full-corpus coverage reach organs a single-query search
# misses (e.g. kidney)?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: corpus-coverage ===
STUDY = 'corpus-coverage'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `coverage-gap-analysis`
#
# **Question.** Which HRA organs and FTUs have ZERO mechanistic-model coverage even at
# full-corpus scale (635/1,730 AS nodes covered across 31/114 organ GLBs),
# and can they be ranked into a prioritized modeling-gap report?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: coverage-gap-analysis ===
STUDY = 'coverage-gap-analysis'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Study: `result-driven-spatial-link`
#
# **Question.** Can the placeholder `readout` string on every (model, AS-node) spatial
# link be replaced with a real steady-state species concentration drawn
# from the committed corpus COPASI/Tellurium comparison dataset, so the 3D
# viewer colors nodes by an actual result instead of by coverage/presence
# alone?

# ### Parameters

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: result-driven-spatial-link ===
STUDY = 'result-driven-spatial-link'
STUDY_DIR = REPO / 'studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ## Open decisions
# - Which HRA organs/FTUs have ZERO mechanistic models (the modeling white-space)?
# - Does organ-granularity coverage overstate AS-level coverage — can we get finer?
# - Can we spatially link model RESULTS (steady-state values) to AS, not just presence?
