"""Importing this package registers viva-human-atlas @composite_generator entries."""
from viva_human_atlas.composites import glucose_regulation  # noqa: F401
from viva_human_atlas.composites import hra_steps  # noqa: F401
from viva_human_atlas.composites import biomodel_do_composite  # noqa: F401
from viva_human_atlas.composites import coverage_composite  # noqa: F401
from viva_human_atlas.composites import corpus_coverage_composite  # noqa: F401
from viva_human_atlas.composites import spatial_link_composite  # noqa: F401
from viva_human_atlas.composites import ftu_coverage_composite  # noqa: F401
from viva_human_atlas.composites import ctpop_islet_composite  # noqa: F401
from viva_human_atlas.composites import vasculature_network_composite  # noqa: F401
